# Default colors
[colors.primary]
background = '#1e1c31'
foreground = '#cbe1e7'

[colors.cursor]
text = '#ff271d'
cursor = '#fbfcfc'

# Normal colors
[colors.normal]
black   = '#141228'
red     = '#ff5458'
green   = '#62d196'
yellow  = '#ffb378'
blue    = '#65b2ff'
magenta = '#906cff'
cyan    = '#63f2f1'
white   = '#a6b3cc'

# Bright colors
[colors.bright]
black   = '#565575'
red     = '#ff8080'
green   = '#95ffa4'
yellow  = '#ffe9aa'
blue    = '#91ddff'
magenta = '#c991e1'
cyan    = '#aaffe4'
white   = '#cbe3e7'

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"


[window]
opacity = 1
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true

  [window.dimensions]
  columns = 110
  lines = 35

  [window.padding]
  x = 5
  y = 5

[cursor]
style = {shape = "Block", blinking = "Always" }
blink_interval = 250
unfocused_hollow = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }

#builtin_box_drawing = false


